"""Generate and validate deterministic macOS release evidence for Loci.

The tool inspects an already-built ``.app`` and, optionally, its distribution
ZIP.  It does not sign, notarize, upload, publish, or modify either artifact.
Public-release validation is deliberately fail-closed: a local ad-hoc package
can produce an evidence report, but it cannot pass the public gate.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import plistlib
import re
import stat
import subprocess
import sys
import tempfile
import zipfile
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Any

REPORT_SCHEMA = "loci.macos-release-evidence/v1"
TREE_HASH_ALGORITHM = "loci-canonical-tree/v1"
SBOM_FORMAT = "CycloneDX"
SUPPORTED_CYCLONEDX_SPEC_VERSIONS = frozenset({"1.4", "1.5", "1.6"})
CYCLONEDX_COMPONENT_TYPES = frozenset(
    {
        "application",
        "container",
        "cryptographic-asset",
        "data",
        "device",
        "device-driver",
        "file",
        "firmware",
        "framework",
        "library",
        "machine-learning-model",
        "operating-system",
        "platform",
    }
)
EXPECTED_BUNDLE_ID = "science.loci.desktop"
EXPECTED_LOCKS = (
    "desktop/package-lock.json",
    "engine/uv.lock",
    "modeling/uv.lock",
)
REQUIRED_NOTICES = (
    "ELECTRON_LICENSE",
    "LICENSES.chromium.html",
    "LOCI_LICENSE",
    "LOCI_NOTICE",
    "THIRD_PARTY_NOTICES.md",
)
REQUIRED_SBOMS = ("desktop", "engine")
HASH_CHUNK_BYTES = 8 * 1024 * 1024
MAX_LICENSE_ARCHIVE_UNCOMPRESSED_BYTES = 512 * 1024 * 1024
# Deep verification of the current Cellpose-enabled app routinely takes about
# a minute because codesign walks the 1+ GiB frozen runtime. Other metadata
# probes remain short so one unavailable system service cannot stall every step.
COMMAND_TIMEOUT_SECONDS = 30
DEEP_CODESIGN_TIMEOUT_SECONDS = 180
REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
SHA256_PATTERN = re.compile(r"^[0-9a-f]{64}$")
GIT_OID_PATTERN = re.compile(r"^(?:[0-9a-f]{40}|[0-9a-f]{64})$")
TEAM_ID_PATTERN = re.compile(r"^[A-Z0-9]{10}$")
SUPPORTED_ARCHITECTURES = frozenset({"arm64", "x86_64"})


class EvidenceError(RuntimeError):
    """An actionable error that prevents trustworthy evidence publication."""


@dataclass(frozen=True, slots=True)
class CommandResult:
    returncode: int
    output: str


CommandRunner = Callable[[Sequence[str], Path | None], CommandResult]


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Inspect an existing Loci macOS app and produce deterministic release evidence. "
            "This command never signs, notarizes, uploads, or publishes artifacts."
        ),
        epilog=(
            "Examples:\n"
            "  python scripts/release_evidence.py collect --app /abs/Loci.app "
            "--output /abs/loci-release.json\n"
            "  python scripts/release_evidence.py check --report /abs/loci-release.json"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    collect = subparsers.add_parser(
        "collect",
        help="Inspect a final app bundle and write a deterministic JSON evidence report.",
    )
    collect.add_argument("--app", required=True, metavar="ABSOLUTE_LOCI_APP")
    collect.add_argument(
        "--repository",
        default=os.fspath(REPOSITORY_ROOT),
        metavar="ABSOLUTE_REPOSITORY",
        help="Git checkout whose source and lock files produced the app.",
    )
    collect.add_argument("--zip", dest="distribution_zip", metavar="ABSOLUTE_ZIP")
    collect.add_argument(
        "--sbom",
        action="append",
        default=[],
        metavar="LABEL=ABSOLUTE_CYCLONEDX_JSON",
        help=(
            "CycloneDX evidence keyed by component. Public readiness requires desktop and "
            "engine labels. Repeat for additional SBOMs."
        ),
    )
    collect.add_argument(
        "--license-archive",
        metavar="ABSOLUTE_ZIP",
        help="Non-empty ZIP containing the release's dependency licence archive.",
    )
    collect.add_argument(
        "--clean-mac-evidence",
        metavar="ABSOLUTE_JSON",
        help="Explicit clean-Mac test attestation described in docs/RELEASE_EVIDENCE.md.",
    )
    collect.add_argument(
        "--public-authorization",
        metavar="ABSOLUTE_JSON",
        help="Explicit human public-release authorization; never generated by this tool.",
    )
    collect.add_argument("--output", required=True, metavar="ABSOLUTE_JSON")
    collect.add_argument(
        "--overwrite",
        action="store_true",
        help="Explicitly replace an existing regular JSON report; symbolic links are refused.",
    )
    collect.add_argument(
        "--public-ready",
        action="store_true",
        help="Write the report, then exit non-zero unless every public-release gate passes.",
    )

    check = subparsers.add_parser(
        "check", help="Validate a previously generated evidence report."
    )
    check.add_argument("--report", required=True, metavar="ABSOLUTE_JSON")
    check.add_argument(
        "--public-ready",
        action="store_true",
        help=(
            "Fail closed for stored unsigned JSON. Re-run collect --public-ready against the "
            "live artifacts to establish readiness."
        ),
    )

    verify_assets = subparsers.add_parser(
        "verify-assets",
        help="Verify release assets in a directory against expected SHA-256 digests or an evidence report.",
    )
    verify_assets.add_argument(
        "--directory",
        required=True,
        metavar="ABSOLUTE_DIRECTORY",
        help="Directory containing release asset files to verify.",
    )
    verify_assets.add_argument(
        "--checksums",
        metavar="ABSOLUTE_JSON",
        help="JSON file mapping asset filenames to expected lowercase SHA-256 hex strings.",
    )
    verify_assets.add_argument(
        "--report",
        metavar="ABSOLUTE_JSON",
        help="Evidence report JSON from which expected asset checksums are derived.",
    )
    return parser


def _absolute_path(value: str, *, label: str) -> Path:
    path = Path(value).expanduser()
    if not path.is_absolute():
        raise EvidenceError(f"{label} must be an absolute path: {value}")
    return path


def _lstat_regular(path: Path, *, label: str) -> os.stat_result:
    try:
        file_stat = path.lstat()
    except OSError as exc:
        raise EvidenceError(f"{label} is not readable: {path}") from exc
    if stat.S_ISLNK(file_stat.st_mode):
        raise EvidenceError(
            f"{label} must be a regular file, not a symbolic link: {path}"
        )
    if not stat.S_ISREG(file_stat.st_mode):
        raise EvidenceError(f"{label} must be a regular file: {path}")
    return file_stat


def fingerprint_file(path: Path, *, label: str) -> dict[str, object]:
    """Return a stable SHA-256 identity for one no-follow regular file."""

    before = _lstat_regular(path, label=label)
    flags = os.O_RDONLY
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW
    try:
        descriptor = os.open(path, flags)
    except OSError as exc:
        raise EvidenceError(f"{label} could not be opened safely: {path}") from exc
    digest = hashlib.sha256()
    try:
        opened_before = os.fstat(descriptor)
        if not stat.S_ISREG(opened_before.st_mode):
            raise EvidenceError(f"{label} must remain a regular file: {path}")
        while chunk := os.read(descriptor, HASH_CHUNK_BYTES):
            digest.update(chunk)
        opened_after = os.fstat(descriptor)
    finally:
        os.close(descriptor)
    after = _lstat_regular(path, label=label)
    identity_before = (before.st_dev, before.st_ino, before.st_size, before.st_mtime_ns)
    identity_opened = (
        opened_before.st_dev,
        opened_before.st_ino,
        opened_before.st_size,
        opened_before.st_mtime_ns,
    )
    identity_opened_after = (
        opened_after.st_dev,
        opened_after.st_ino,
        opened_after.st_size,
        opened_after.st_mtime_ns,
    )
    identity_after = (after.st_dev, after.st_ino, after.st_size, after.st_mtime_ns)
    if (
        len({identity_before, identity_opened, identity_opened_after, identity_after})
        != 1
    ):
        raise EvidenceError(f"{label} changed while SHA-256 was being computed: {path}")
    return {"sha256": digest.hexdigest(), "size_bytes": int(after.st_size)}


def _canonical_record(digest: Any, record: Mapping[str, object]) -> None:
    encoded = json.dumps(
        record, sort_keys=True, separators=(",", ":"), ensure_ascii=True
    )
    digest.update(encoded.encode("utf-8"))
    digest.update(b"\n")


def fingerprint_tree(root: Path) -> dict[str, object]:
    """Hash paths, types, POSIX modes, symlink targets, and regular-file contents."""

    try:
        root_stat = root.lstat()
    except OSError as exc:
        raise EvidenceError(f"App bundle is not readable: {root}") from exc
    if stat.S_ISLNK(root_stat.st_mode) or not stat.S_ISDIR(root_stat.st_mode):
        raise EvidenceError(f"App bundle must be a real directory, not a link: {root}")

    digest = hashlib.sha256()
    digest.update(f"{TREE_HASH_ALGORITHM}\n".encode())
    counts = {"directories": 1, "files": 0, "symlinks": 0}
    total_bytes = 0
    _canonical_record(
        digest,
        {"mode": stat.S_IMODE(root_stat.st_mode), "path": ".", "type": "directory"},
    )

    def visit(directory: Path, relative: PurePosixPath) -> None:
        nonlocal total_bytes
        before = directory.stat(follow_symlinks=False)
        try:
            with os.scandir(directory) as iterator:
                children = sorted(iterator, key=lambda entry: entry.name)
        except OSError as exc:
            raise EvidenceError(
                f"Could not enumerate app bundle directory: {directory}"
            ) from exc
        for child in children:
            child_path = Path(child.path)
            child_relative = relative / child.name
            try:
                child_stat = child.stat(follow_symlinks=False)
            except OSError as exc:
                raise EvidenceError(
                    f"Could not inspect app bundle entry: {child_path}"
                ) from exc
            mode = stat.S_IMODE(child_stat.st_mode)
            if stat.S_ISLNK(child_stat.st_mode):
                try:
                    target = os.readlink(child_path)
                except OSError as exc:
                    raise EvidenceError(
                        f"Could not read app bundle link: {child_path}"
                    ) from exc
                _canonical_record(
                    digest,
                    {
                        "mode": mode,
                        "path": child_relative.as_posix(),
                        "target": target,
                        "type": "symlink",
                    },
                )
                counts["symlinks"] += 1
            elif stat.S_ISDIR(child_stat.st_mode):
                _canonical_record(
                    digest,
                    {
                        "mode": mode,
                        "path": child_relative.as_posix(),
                        "type": "directory",
                    },
                )
                counts["directories"] += 1
                visit(child_path, child_relative)
            elif stat.S_ISREG(child_stat.st_mode):
                identity = fingerprint_file(child_path, label="App bundle file")
                _canonical_record(
                    digest,
                    {
                        "mode": mode,
                        "path": child_relative.as_posix(),
                        "sha256": identity["sha256"],
                        "size_bytes": identity["size_bytes"],
                        "type": "file",
                    },
                )
                counts["files"] += 1
                total_bytes += int(identity["size_bytes"])
            else:
                raise EvidenceError(
                    f"Unsupported special file in app bundle: {child_relative.as_posix()}"
                )
        after = directory.stat(follow_symlinks=False)
        before_identity = (
            before.st_dev,
            before.st_ino,
            before.st_mtime_ns,
            before.st_mode,
        )
        after_identity = (after.st_dev, after.st_ino, after.st_mtime_ns, after.st_mode)
        if before_identity != after_identity:
            raise EvidenceError(
                f"App bundle changed while it was being hashed: {directory}"
            )

    visit(root, PurePosixPath())
    return {
        "algorithm": TREE_HASH_ALGORITHM,
        "sha256": digest.hexdigest(),
        "size_bytes": total_bytes,
        **counts,
    }


def _default_runner(arguments: Sequence[str], cwd: Path | None = None) -> CommandResult:
    environment = dict(os.environ)
    environment.update({"LANG": "C", "LC_ALL": "C"})
    timeout = COMMAND_TIMEOUT_SECONDS
    if Path(arguments[0]).name == "codesign" and "--verify" in arguments:
        timeout = DEEP_CODESIGN_TIMEOUT_SECONDS
    try:
        completed = subprocess.run(
            list(arguments),
            cwd=cwd,
            env=environment,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            timeout=timeout,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        return CommandResult(
            returncode=127, output=f"command unavailable: {type(exc).__name__}"
        )
    return CommandResult(completed.returncode, completed.stdout)


def _line_value(output: str, key: str) -> str | None:
    prefix = f"{key}="
    for line in output.splitlines():
        if line.startswith(prefix):
            value = line[len(prefix) :].strip()
            return None if value in {"", "not set"} else value
    return None


def inspect_bundle(
    app: Path, runner: CommandRunner = _default_runner
) -> dict[str, object]:
    info_path = app / "Contents" / "Info.plist"
    _lstat_regular(info_path, label="App Info.plist")
    try:
        with info_path.open("rb") as stream:
            info = plistlib.load(stream)
    except (OSError, plistlib.InvalidFileException) as exc:
        raise EvidenceError(f"App Info.plist is invalid: {info_path}") from exc
    if not isinstance(info, dict):
        raise EvidenceError("App Info.plist must contain a dictionary.")
    executable_name = info.get("CFBundleExecutable")
    if not isinstance(executable_name, str) or not executable_name:
        raise EvidenceError("App Info.plist is missing CFBundleExecutable.")
    if Path(executable_name).name != executable_name:
        raise EvidenceError(
            "CFBundleExecutable must be a filename within Contents/MacOS."
        )
    executable = app / "Contents" / "MacOS" / executable_name
    _lstat_regular(executable, label="App executable")
    architecture_result = runner(
        ("/usr/bin/lipo", "-archs", os.fspath(executable)), None
    )
    architectures = (
        sorted(set(architecture_result.output.strip().split()))
        if architecture_result.returncode == 0
        else []
    )
    return {
        "bundle_id": info.get("CFBundleIdentifier"),
        "bundle_version": info.get("CFBundleVersion"),
        "display_name": info.get("CFBundleDisplayName") or info.get("CFBundleName"),
        "executable": executable_name,
        "minimum_macos": info.get("LSMinimumSystemVersion"),
        "short_version": info.get("CFBundleShortVersionString"),
        "architectures": architectures,
    }


def inspect_signature(
    app: Path, runner: CommandRunner = _default_runner
) -> dict[str, object]:
    verification = runner(
        ("/usr/bin/codesign", "--verify", "--deep", "--strict", os.fspath(app)), None
    )
    details = runner(("/usr/bin/codesign", "-dv", "--verbose=4", os.fspath(app)), None)
    output = details.output
    authorities = [
        line.removeprefix("Authority=").strip()
        for line in output.splitlines()
        if line.startswith("Authority=")
    ]
    signature_value = _line_value(output, "Signature")
    flags_line = next(
        (line for line in output.splitlines() if line.startswith("CodeDirectory ")), ""
    )
    if details.returncode != 0:
        mode = "unsigned"
    elif signature_value == "adhoc" or "(adhoc)" in flags_line:
        mode = "ad-hoc"
    elif any(
        authority.startswith("Developer ID Application:") for authority in authorities
    ):
        mode = "developer-id"
    else:
        mode = "other"
    timestamp = _line_value(output, "Timestamp") or _line_value(output, "Signed Time")
    return {
        "authorities": authorities,
        "hardened_runtime": "(runtime)" in flags_line,
        "mode": mode,
        "team_id": _line_value(output, "TeamIdentifier"),
        "timestamp": timestamp,
        "verified_deep_strict": verification.returncode == 0,
    }


def inspect_notarization(
    app: Path, runner: CommandRunner = _default_runner
) -> dict[str, object]:
    assessment = runner(
        (
            "/usr/sbin/spctl",
            "--assess",
            "--type",
            "execute",
            "--verbose=4",
            os.fspath(app),
        ),
        None,
    )
    source = _line_value(assessment.output, "source")
    accepted = assessment.returncode == 0 and "accepted" in assessment.output.lower()
    notarized = accepted and bool(source and "notarized developer id" in source.lower())
    if notarized:
        status_value = "notarized"
    elif accepted:
        status_value = "accepted-not-notarized"
    elif assessment.returncode == 127:
        status_value = "unavailable"
    else:
        status_value = "rejected"
    staple = runner(("/usr/bin/xcrun", "stapler", "validate", os.fspath(app)), None)
    return {
        "gatekeeper": {
            "accepted": accepted,
            "notarized": notarized,
            "source": source,
            "status": status_value,
        },
        "staple": {
            "status": "valid" if staple.returncode == 0 else "missing-or-invalid",
            "valid": staple.returncode == 0,
        },
    }


def inspect_notices(app: Path) -> dict[str, object]:
    notice_root = app / "Contents" / "Resources" / "notices"
    inventory: dict[str, object] = {}
    for filename in REQUIRED_NOTICES:
        path = notice_root / filename
        try:
            identity = fingerprint_file(path, label=f"Required notice {filename}")
        except EvidenceError:
            inventory[filename] = {"present": False, "sha256": None, "size_bytes": 0}
        else:
            inventory[filename] = {"present": True, **identity}
    return inventory


def inspect_repository(
    repository: Path, runner: CommandRunner = _default_runner
) -> dict[str, object]:
    if repository.is_symlink() or not repository.is_dir():
        raise EvidenceError(f"Repository must be a real directory: {repository}")
    commit_result = runner(
        ("/usr/bin/git", "rev-parse", "--verify", "HEAD"), repository
    )
    status_result = runner(
        ("/usr/bin/git", "status", "--porcelain=v1", "-z", "--untracked-files=all"),
        repository,
    )
    commit = commit_result.output.strip() if commit_result.returncode == 0 else None
    status_bytes = status_result.output.encode("utf-8", errors="surrogateescape")
    locks: dict[str, object] = {}
    for relative in EXPECTED_LOCKS:
        path = repository / relative
        try:
            locks[relative] = {
                "present": True,
                **fingerprint_file(path, label="Lock file"),
            }
        except EvidenceError:
            locks[relative] = {"present": False, "sha256": None, "size_bytes": 0}
    return {
        "commit": commit,
        "dirty": status_result.returncode != 0 or bool(status_bytes),
        "git_available": commit_result.returncode == 0
        and status_result.returncode == 0,
        "locks": locks,
        "status_sha256": hashlib.sha256(status_bytes).hexdigest(),
    }


def _safe_zip_member(name: str) -> bool:
    normalized = name.replace("\\", "/")
    path = PurePosixPath(normalized)
    return (
        bool(normalized)
        and not path.is_absolute()
        and ".." not in path.parts
        and not re.match(r"^[A-Za-z]:", normalized)
    )


def _zip_member_kind(member: zipfile.ZipInfo) -> str:
    mode = (member.external_attr >> 16) & 0xFFFF
    file_type = stat.S_IFMT(mode)
    if member.is_dir():
        if file_type not in {0, stat.S_IFDIR}:
            raise EvidenceError(
                f"ZIP directory has conflicting mode: {member.filename}"
            )
        return "directory"
    if file_type == stat.S_IFLNK:
        return "symlink"
    if file_type in {0, stat.S_IFREG}:
        return "file"
    raise EvidenceError(f"ZIP contains an unsupported special file: {member.filename}")


def _zip_app_tree(
    archive: zipfile.ZipFile,
    members: Sequence[zipfile.ZipInfo],
    *,
    root_name: str,
) -> dict[str, object]:
    records: dict[str, dict[str, object]] = {}
    file_size_total = 0

    for member in members:
        normalized = member.filename.replace("\\", "/")
        parts = PurePosixPath(normalized).parts
        if not parts or parts[0] != root_name:
            raise EvidenceError(
                "Distribution ZIP contains entries outside the app root."
            )
        relative_parts = parts[1:]
        relative = PurePosixPath(*relative_parts).as_posix() if relative_parts else "."
        if relative in records:
            raise EvidenceError(
                f"Distribution ZIP contains a duplicate path: {relative}"
            )
        kind = _zip_member_kind(member)
        mode = stat.S_IMODE((member.external_attr >> 16) & 0xFFFF)
        if relative == "." and kind != "directory":
            raise EvidenceError("Distribution ZIP app root is not a directory.")
        if kind == "directory":
            record: dict[str, object] = {
                "mode": mode,
                "path": relative,
                "type": "directory",
            }
        elif kind == "symlink":
            if member.file_size > 65_536:
                raise EvidenceError(
                    f"ZIP symlink target is unreasonably large: {relative}"
                )
            target_bytes = archive.read(member)
            target = target_bytes.decode("utf-8", errors="surrogateescape")
            record = {
                "mode": mode,
                "path": relative,
                "target": target,
                "type": "symlink",
            }
        else:
            digest = hashlib.sha256()
            size = 0
            with archive.open(member) as stream:
                while chunk := stream.read(HASH_CHUNK_BYTES):
                    digest.update(chunk)
                    size += len(chunk)
            if size != member.file_size:
                raise EvidenceError(
                    f"ZIP member size changed while reading: {relative}"
                )
            record = {
                "mode": mode,
                "path": relative,
                "sha256": digest.hexdigest(),
                "size_bytes": size,
                "type": "file",
            }
            file_size_total += size
        records[relative] = record

    root = records.get(".")
    if root is None:
        raise EvidenceError(
            "Distribution ZIP is missing an explicit app-root directory."
        )

    children: dict[str, list[str]] = {path: [] for path in records}
    for relative, record in records.items():
        if relative == ".":
            continue
        parent = PurePosixPath(relative).parent.as_posix()
        if parent in {"", "."}:
            parent = "."
        parent_record = records.get(parent)
        if parent_record is None or parent_record.get("type") != "directory":
            raise EvidenceError(
                f"Distribution ZIP omits parent directory for: {relative}"
            )
        children[parent].append(relative)

    digest = hashlib.sha256()
    digest.update(f"{TREE_HASH_ALGORITHM}\n".encode())
    _canonical_record(digest, root)

    def visit(parent: str) -> None:
        for relative in sorted(
            children[parent], key=lambda value: PurePosixPath(value).name
        ):
            record = records[relative]
            _canonical_record(digest, record)
            if record["type"] == "directory":
                visit(relative)

    visit(".")
    return {
        "algorithm": TREE_HASH_ALGORITHM,
        "sha256": digest.hexdigest(),
        "size_bytes": file_size_total,
        "directories": sum(
            record["type"] == "directory" for record in records.values()
        ),
        "files": sum(record["type"] == "file" for record in records.values()),
        "symlinks": sum(record["type"] == "symlink" for record in records.values()),
    }


def _validate_license_payloads(
    archive: zipfile.ZipFile, members: Sequence[zipfile.ZipInfo]
) -> int:
    uncompressed_size = sum(member.file_size for member in members)
    if uncompressed_size > MAX_LICENSE_ARCHIVE_UNCOMPRESSED_BYTES:
        raise EvidenceError(
            "Licence archive exceeds the bounded uncompressed-size limit."
        )
    payload_files = 0
    for member in members:
        if _zip_member_kind(member) != "file":
            continue
        with archive.open(member) as stream:
            size = 0
            while chunk := stream.read(HASH_CHUNK_BYTES):
                size += len(chunk)
        if size != member.file_size:
            raise EvidenceError(
                f"ZIP member size changed while reading: {member.filename}"
            )
        if size > 0:
            payload_files += 1
    return payload_files


def inspect_zip(
    path: Path,
    *,
    label: str,
    require_app: bool,
    expected_app_name: str | None = None,
    expected_tree: Mapping[str, object] | None = None,
) -> dict[str, object]:
    identity = fingerprint_file(path, label=label)
    valid = True
    reasons: list[str] = []
    entries = 0
    payload_files = 0
    app_root: str | None = None
    app_tree: dict[str, object] | None = None
    matches_app_tree: bool | None = None
    license_manifest_schema: str | None = None
    license_component_count = 0
    license_coverage_complete = False
    license_inputs: object = None
    try:
        with zipfile.ZipFile(path) as archive:
            members = archive.infolist()
            entries = len(members)
            unsafe = [
                member.filename
                for member in members
                if not _safe_zip_member(member.filename)
            ]
            if unsafe:
                raise EvidenceError(
                    "archive contains unsafe absolute, drive-qualified, or parent-traversal names"
                )
            if not members:
                raise EvidenceError("archive is empty")
            if require_app:
                app_roots = {
                    PurePosixPath(member.filename.replace("\\", "/")).parts[0]
                    for member in members
                    if PurePosixPath(member.filename.replace("\\", "/")).parts
                    and PurePosixPath(member.filename.replace("\\", "/"))
                    .parts[0]
                    .endswith(".app")
                }
                if len(app_roots) != 1:
                    raise EvidenceError(
                        "distribution archive must contain exactly one top-level .app root"
                    )
                app_root = next(iter(app_roots))
                if expected_app_name is not None and app_root != expected_app_name:
                    raise EvidenceError(
                        f"distribution app root is {app_root}, expected {expected_app_name}"
                    )
                if expected_tree is None:
                    raise EvidenceError(
                        "distribution ZIP requires an expected app-tree identity"
                    )
                declared_kinds = [_zip_member_kind(member) for member in members]
                declared_shape = {
                    "directories": declared_kinds.count("directory"),
                    "files": declared_kinds.count("file"),
                    "symlinks": declared_kinds.count("symlink"),
                    "size_bytes": sum(
                        member.file_size
                        for member, kind in zip(members, declared_kinds, strict=True)
                        if kind == "file"
                    ),
                }
                if any(
                    expected_tree.get(key) != value
                    for key, value in declared_shape.items()
                ):
                    raise EvidenceError(
                        "distribution ZIP declared tree shape does not match the inspected app"
                    )
                app_tree = _zip_app_tree(archive, members, root_name=app_root)
                matches_app_tree = app_tree == dict(expected_tree)
                if not matches_app_tree:
                    raise EvidenceError(
                        "distribution ZIP app tree does not match the inspected app tree"
                    )
            else:
                # Public readiness requires the deterministic manifest contract,
                # exact payload set, and per-file checksums produced by the
                # release supply-chain tool. A generic non-empty ZIP is not
                # evidence of dependency coverage.
                try:
                    from scripts.release_supply_chain import inspect_license_archive
                except ImportError:
                    from release_supply_chain import inspect_license_archive

                license_result = inspect_license_archive(path)
                payload_files = int(license_result.get("evidence_files", 0))
                license_manifest_schema = license_result.get("manifest_schema")
                license_component_count = int(license_result.get("component_count", 0))
                license_coverage_complete = (
                    license_result.get("coverage_complete") is True
                )
                license_inputs = license_result.get("inputs")
                if license_result.get("valid") is not True:
                    raise EvidenceError(
                        "; ".join(license_result.get("reasons", []))
                        or "dependency licence manifest is invalid"
                    )
    except (EvidenceError, OSError, RuntimeError, zipfile.BadZipFile) as exc:
        valid = False
        reasons.append(str(exc) or "file is not a readable ZIP archive")
    confirmed_identity = fingerprint_file(path, label=label)
    if confirmed_identity != identity:
        raise EvidenceError(
            f"{label} changed while its ZIP structure was being inspected."
        )
    return {
        **identity,
        "entries": entries,
        "payload_files": payload_files,
        "app_root": app_root,
        "app_tree": app_tree,
        "matches_app_tree": matches_app_tree,
        "manifest_schema": license_manifest_schema,
        "component_count": license_component_count,
        "coverage_complete": license_coverage_complete,
        "inputs": license_inputs,
        "valid": valid,
        "reasons": reasons,
    }


def _read_json_evidence(
    path: Path, *, label: str
) -> tuple[dict[str, Any], dict[str, object]]:
    identity = fingerprint_file(path, label=label)
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise EvidenceError(f"{label} must be valid UTF-8 JSON: {path}") from exc
    if not isinstance(raw, dict):
        raise EvidenceError(f"{label} must contain one JSON object: {path}")
    if fingerprint_file(path, label=label) != identity:
        raise EvidenceError(f"{label} changed while it was being read: {path}")
    return raw, identity


def inspect_sbom(path: Path, *, label: str) -> dict[str, object]:
    raw, identity = _read_json_evidence(path, label=f"SBOM {label}")
    components = raw.get("components")
    components_valid = isinstance(components, list) and bool(components)
    if components_valid:
        components_valid = all(
            isinstance(component, Mapping)
            and isinstance(component.get("name"), str)
            and bool(component["name"].strip())
            and component.get("type") in CYCLONEDX_COMPONENT_TYPES
            for component in components
        )
    valid = (
        raw.get("bomFormat") == SBOM_FORMAT
        and raw.get("specVersion") in SUPPORTED_CYCLONEDX_SPEC_VERSIONS
        and components_valid
    )
    reasons = (
        []
        if valid
        else [
            "expected a supported CycloneDX JSON document with named, typed components"
        ]
    )
    return {
        **identity,
        "bom_format": raw.get("bomFormat"),
        "component_count": len(components) if isinstance(components, list) else 0,
        "spec_version": raw.get("specVersion"),
        "valid": valid,
        "reasons": reasons,
    }


def inspect_clean_mac_evidence(path: Path, *, app_sha256: str) -> dict[str, object]:
    raw, identity = _read_json_evidence(path, label="Clean-Mac evidence")
    reasons: list[str] = []
    if raw.get("schema") != "loci.clean-mac-evidence/v1":
        reasons.append("schema must be loci.clean-mac-evidence/v1")
    if raw.get("passed") is not True:
        reasons.append("passed must be true")
    if raw.get("environment_is_clean") is not True:
        reasons.append("environment_is_clean must be true")
    if raw.get("app_tree_sha256") != app_sha256:
        reasons.append("app_tree_sha256 does not match this app")
    if not isinstance(raw.get("test_run_id"), str) or not raw["test_run_id"].strip():
        reasons.append("test_run_id must be a non-empty string")
    return {
        **identity,
        "app_tree_sha256": raw.get("app_tree_sha256"),
        "schema": raw.get("schema"),
        "test_run_id": raw.get("test_run_id"),
        "valid": not reasons,
        "reasons": reasons,
    }


def inspect_public_authorization(
    path: Path, *, app_sha256: str, release_version: object
) -> dict[str, object]:
    raw, identity = _read_json_evidence(path, label="Public-release authorization")
    reasons: list[str] = []
    if raw.get("schema") != "loci.public-release-authorization/v1":
        reasons.append("schema must be loci.public-release-authorization/v1")
    if raw.get("authorized") is not True:
        reasons.append("authorized must be true")
    if raw.get("app_tree_sha256") != app_sha256:
        reasons.append("app_tree_sha256 does not match this app")
    if raw.get("release_version") != release_version:
        reasons.append("release_version does not match this app")
    if (
        not isinstance(raw.get("authorization_id"), str)
        or not raw["authorization_id"].strip()
    ):
        reasons.append("authorization_id must be a non-empty string")
    return {
        **identity,
        "app_tree_sha256": raw.get("app_tree_sha256"),
        "authorization_id": raw.get("authorization_id"),
        "release_version": raw.get("release_version"),
        "schema": raw.get("schema"),
        "valid": not reasons,
        "reasons": reasons,
    }


def _parse_sbom_arguments(values: Sequence[str]) -> dict[str, Path]:
    parsed: dict[str, Path] = {}
    for value in values:
        label, separator, path_value = value.partition("=")
        if not separator or not re.fullmatch(r"[a-z0-9][a-z0-9-]*", label):
            raise EvidenceError(
                f"SBOM must use a lowercase LABEL=ABSOLUTE_PATH value: {value}"
            )
        if label in parsed:
            raise EvidenceError(f"Duplicate SBOM label: {label}")
        parsed[label] = _absolute_path(path_value, label=f"SBOM {label}")
    return parsed


def _resolved_path(path: Path, *, label: str) -> Path:
    try:
        return path.resolve(strict=False)
    except (OSError, RuntimeError) as exc:
        raise EvidenceError(f"Could not resolve {label} safely: {path}") from exc


def _paths_alias(left: Path, right: Path) -> bool:
    if _resolved_path(left, label="output report") == _resolved_path(
        right, label="protected evidence input"
    ):
        return True
    try:
        return left.exists() and right.exists() and os.path.samefile(left, right)
    except OSError:
        return False


def validate_collect_output(arguments: argparse.Namespace, output: Path) -> None:
    resolved_output = _resolved_path(output, label="output report")
    app = _resolved_path(
        _absolute_path(arguments.app, label="App bundle"), label="app bundle"
    )
    repository = _resolved_path(
        _absolute_path(arguments.repository, label="Repository"),
        label="release repository",
    )
    for root, label in ((app, "app bundle"), (repository, "release repository")):
        if resolved_output == root or root in resolved_output.parents:
            raise EvidenceError(
                f"Output report must be outside the {label} so publication cannot invalidate evidence."
            )

    protected_files: list[tuple[Path, str]] = []
    optional_files = (
        (arguments.distribution_zip, "distribution ZIP"),
        (arguments.license_archive, "licence archive"),
        (arguments.clean_mac_evidence, "clean-Mac evidence"),
        (arguments.public_authorization, "public-release authorization"),
    )
    for value, label in optional_files:
        if value:
            protected_files.append((_absolute_path(value, label=label), label))
    protected_files.extend(
        (path, f"SBOM {label}")
        for label, path in _parse_sbom_arguments(arguments.sbom).items()
    )
    for protected, label in protected_files:
        if _paths_alias(output, protected):
            raise EvidenceError(f"Output report must not replace or alias the {label}.")


def _is_sha256(value: object) -> bool:
    return isinstance(value, str) and bool(SHA256_PATTERN.fullmatch(value))


def _is_git_oid(value: object) -> bool:
    return isinstance(value, str) and bool(GIT_OID_PATTERN.fullmatch(value))


def _positive_int(value: object) -> bool:
    return isinstance(value, int) and not isinstance(value, bool) and value > 0


def _nonnegative_int(value: object) -> bool:
    return isinstance(value, int) and not isinstance(value, bool) and value >= 0


def _valid_fingerprint(record: object, *, require_nonempty: bool) -> bool:
    if not isinstance(record, Mapping) or not _is_sha256(record.get("sha256")):
        return False
    size = record.get("size_bytes")
    return _positive_int(size) if require_nonempty else _nonnegative_int(size)


def public_readiness_failures(report: Mapping[str, object]) -> list[str]:
    """Return fixed-order, actionable public-release failures."""

    failures: list[str] = []
    repository = report.get("repository")
    application = report.get("application")
    if not isinstance(repository, Mapping):
        return ["Repository evidence is missing or malformed; regenerate the report."]
    if not isinstance(application, Mapping):
        return ["Application evidence is missing or malformed; regenerate the report."]

    if repository.get("git_available") is not True or not _is_git_oid(
        repository.get("commit")
    ):
        failures.append(
            "Git commit evidence is unavailable; collect from the release checkout."
        )
    if repository.get("dirty") is not False:
        failures.append(
            "The release checkout is dirty; build and collect from a clean commit."
        )
    locks = repository.get("locks")
    if not isinstance(locks, Mapping):
        failures.append(
            "Lock-file evidence is missing; regenerate from the release checkout."
        )
    else:
        for relative in EXPECTED_LOCKS:
            lock = locks.get(relative)
            if (
                not isinstance(lock, Mapping)
                or lock.get("present") is not True
                or not _valid_fingerprint(lock, require_nonempty=True)
            ):
                failures.append(
                    f"Required lock-file evidence is missing or invalid: {relative}."
                )

    tree = application.get("tree")
    if (
        not isinstance(tree, Mapping)
        or tree.get("algorithm") != TREE_HASH_ALGORITHM
        or not _is_sha256(tree.get("sha256"))
        or not _positive_int(tree.get("size_bytes"))
        or not _positive_int(tree.get("directories"))
        or not _positive_int(tree.get("files"))
        or not _nonnegative_int(tree.get("symlinks"))
    ):
        failures.append("Canonical app-tree SHA-256 is missing or invalid.")
    bundle = application.get("bundle")
    if not isinstance(bundle, Mapping):
        failures.append("Bundle metadata is missing or malformed.")
    else:
        if bundle.get("bundle_id") != EXPECTED_BUNDLE_ID:
            failures.append(f"Bundle identifier must be {EXPECTED_BUNDLE_ID}.")
        if (
            not isinstance(bundle.get("short_version"), str)
            or not bundle["short_version"].strip()
        ):
            failures.append("Bundle short version metadata is missing or invalid.")
        if (
            not isinstance(bundle.get("minimum_macos"), str)
            or not bundle["minimum_macos"].strip()
        ):
            failures.append("Bundle version or minimum macOS metadata is missing.")
        architectures = bundle.get("architectures")
        if (
            not isinstance(architectures, list)
            or not architectures
            or any(
                architecture not in SUPPORTED_ARCHITECTURES
                for architecture in architectures
            )
        ):
            failures.append("No executable architecture was verified with lipo.")

    signature = application.get("signature")
    if not isinstance(signature, Mapping):
        failures.append("Code-signature evidence is missing or malformed.")
    else:
        if signature.get("verified_deep_strict") is not True:
            failures.append(
                "The app does not pass deep, strict code-signature verification."
            )
        if signature.get("mode") != "developer-id":
            failures.append(
                "A Developer ID Application signature is required; ad-hoc is not public-ready."
            )
        if not isinstance(
            signature.get("team_id"), str
        ) or not TEAM_ID_PATTERN.fullmatch(signature["team_id"]):
            failures.append("The Developer ID team identifier is missing.")
        if signature.get("hardened_runtime") is not True:
            failures.append("Hardened Runtime is not enabled.")
        if (
            not isinstance(signature.get("timestamp"), str)
            or not signature["timestamp"].strip()
        ):
            failures.append("A trusted signing timestamp is missing.")
        authorities = signature.get("authorities")
        if not isinstance(authorities, list) or not any(
            isinstance(authority, str)
            and authority.startswith("Developer ID Application:")
            for authority in authorities
        ):
            failures.append("Developer ID Application authority evidence is missing.")

    notarization = application.get("notarization")
    if not isinstance(notarization, Mapping):
        failures.append("Notarization evidence is missing or malformed.")
    else:
        gatekeeper = notarization.get("gatekeeper")
        staple = notarization.get("staple")
        if (
            not isinstance(gatekeeper, Mapping)
            or gatekeeper.get("accepted") is not True
            or gatekeeper.get("notarized") is not True
            or gatekeeper.get("status") != "notarized"
            or not isinstance(gatekeeper.get("source"), str)
            or "notarized developer id" not in gatekeeper["source"].lower()
        ):
            failures.append("Gatekeeper does not report a notarized Developer ID app.")
        if (
            not isinstance(staple, Mapping)
            or staple.get("valid") is not True
            or staple.get("status") != "valid"
        ):
            failures.append("A valid stapled notarization ticket is missing.")

    notices = application.get("notices")
    if not isinstance(notices, Mapping):
        failures.append("Required notice inventory is missing.")
    else:
        for filename in REQUIRED_NOTICES:
            notice = notices.get(filename)
            if (
                not isinstance(notice, Mapping)
                or notice.get("present") is not True
                or not _valid_fingerprint(notice, require_nonempty=True)
            ):
                failures.append(
                    f"Required bundled notice is missing or empty: {filename}."
                )

    distribution_zip = report.get("distribution_zip")
    if distribution_zip is not None and (
        not isinstance(distribution_zip, Mapping)
        or distribution_zip.get("valid") is not True
        or distribution_zip.get("matches_app_tree") is not True
        or distribution_zip.get("app_root") != application.get("name")
        or distribution_zip.get("app_tree") != tree
        or not _valid_fingerprint(distribution_zip, require_nonempty=True)
        or distribution_zip.get("reasons") != []
    ):
        failures.append(
            "The supplied distribution ZIP is invalid or does not contain an app."
        )

    sboms = report.get("sboms")
    if not isinstance(sboms, Mapping):
        failures.append("CycloneDX SBOM evidence is missing.")
    else:
        for label in REQUIRED_SBOMS:
            sbom = sboms.get(label)
            if (
                not isinstance(sbom, Mapping)
                or sbom.get("valid") is not True
                or sbom.get("bom_format") != SBOM_FORMAT
                or sbom.get("spec_version") not in SUPPORTED_CYCLONEDX_SPEC_VERSIONS
                or not _positive_int(sbom.get("component_count"))
                or not _valid_fingerprint(sbom, require_nonempty=True)
                or sbom.get("reasons") != []
            ):
                failures.append(f"A valid CycloneDX {label} SBOM is required.")

    license_archive = report.get("license_archive")
    expected_license_inputs: dict[str, object] | None = None
    if (
        isinstance(tree, Mapping)
        and isinstance(locks, Mapping)
        and isinstance(sboms, Mapping)
        and isinstance(locks.get("desktop/package-lock.json"), Mapping)
        and isinstance(locks.get("engine/uv.lock"), Mapping)
        and isinstance(sboms.get("desktop"), Mapping)
        and isinstance(sboms.get("engine"), Mapping)
    ):
        expected_license_inputs = {
            "app_tree_sha256": tree.get("sha256"),
            "desktop_lock_sha256": locks["desktop/package-lock.json"].get("sha256"),
            "engine_lock_sha256": locks["engine/uv.lock"].get("sha256"),
            "sboms": {
                "desktop": sboms["desktop"].get("sha256"),
                "engine": sboms["engine"].get("sha256"),
            },
        }
    if (
        not isinstance(license_archive, Mapping)
        or license_archive.get("valid") is not True
        or not _valid_fingerprint(license_archive, require_nonempty=True)
        or not _positive_int(license_archive.get("entries"))
        or not _positive_int(license_archive.get("payload_files"))
        or license_archive.get("manifest_schema") != "loci.dependency-licences/v1"
        or not _positive_int(license_archive.get("component_count"))
        or license_archive.get("coverage_complete") is not True
        or license_archive.get("inputs") != expected_license_inputs
        or license_archive.get("reasons") != []
    ):
        failures.append(
            "A complete, checksummed dependency licence archive is required."
        )

    clean_mac = report.get("clean_mac_evidence")
    tree_sha256 = tree.get("sha256") if isinstance(tree, Mapping) else None
    if (
        not isinstance(clean_mac, Mapping)
        or clean_mac.get("valid") is not True
        or clean_mac.get("schema") != "loci.clean-mac-evidence/v1"
        or clean_mac.get("app_tree_sha256") != tree_sha256
        or not isinstance(clean_mac.get("test_run_id"), str)
        or not clean_mac["test_run_id"].strip()
        or not _valid_fingerprint(clean_mac, require_nonempty=True)
        or clean_mac.get("reasons") != []
    ):
        failures.append(
            "Passing clean-Mac evidence bound to this exact app is required."
        )

    authorization = report.get("public_authorization")
    release_version = (
        bundle.get("short_version") if isinstance(bundle, Mapping) else None
    )
    if (
        not isinstance(authorization, Mapping)
        or authorization.get("valid") is not True
        or authorization.get("schema") != "loci.public-release-authorization/v1"
        or authorization.get("app_tree_sha256") != tree_sha256
        or authorization.get("release_version") != release_version
        or not isinstance(authorization.get("authorization_id"), str)
        or not authorization["authorization_id"].strip()
        or not _valid_fingerprint(authorization, require_nonempty=True)
        or authorization.get("reasons") != []
    ):
        failures.append(
            "Explicit human authorization for this exact public release is required."
        )
    return failures


def validate_report_structure(report: object) -> Mapping[str, object]:
    if not isinstance(report, Mapping):
        raise EvidenceError("Evidence report must contain one JSON object.")
    if report.get("schema") != REPORT_SCHEMA:
        raise EvidenceError(f"Evidence report schema must be {REPORT_SCHEMA}.")
    recorded = report.get("public_readiness")
    if not isinstance(recorded, Mapping):
        raise EvidenceError("Evidence report is missing public_readiness.")
    expected_failures = public_readiness_failures(report)
    if (
        recorded.get("ready") is not (not expected_failures)
        or recorded.get("failures") != expected_failures
    ):
        raise EvidenceError(
            "Recorded public_readiness does not match the evidence; regenerate the report."
        )
    return report


def collect_report(
    arguments: argparse.Namespace, *, runner: CommandRunner = _default_runner
) -> dict[str, object]:
    app = _absolute_path(arguments.app, label="App bundle")
    repository = _absolute_path(arguments.repository, label="Repository")
    if app.suffix != ".app":
        raise EvidenceError(f"App bundle must end in .app: {app}")
    tree = fingerprint_tree(app)
    bundle = inspect_bundle(app, runner)
    app_sha256 = str(tree["sha256"])
    release_version = bundle.get("short_version")

    distribution_zip = None
    zip_path: Path | None = None
    if arguments.distribution_zip:
        zip_path = _absolute_path(arguments.distribution_zip, label="Distribution ZIP")
        distribution_zip = inspect_zip(
            zip_path,
            label="Distribution ZIP",
            require_app=True,
            expected_app_name=app.name,
            expected_tree=tree,
        )

    sbom_paths = _parse_sbom_arguments(arguments.sbom)
    sboms = {
        label: inspect_sbom(path, label=label)
        for label, path in sorted(sbom_paths.items())
    }
    license_archive = None
    license_path: Path | None = None
    if arguments.license_archive:
        license_path = _absolute_path(
            arguments.license_archive, label="Licence archive"
        )
        license_archive = inspect_zip(
            license_path, label="Licence archive", require_app=False
        )

    clean_mac = None
    clean_path: Path | None = None
    if arguments.clean_mac_evidence:
        clean_path = _absolute_path(
            arguments.clean_mac_evidence, label="Clean-Mac evidence"
        )
        clean_mac = inspect_clean_mac_evidence(clean_path, app_sha256=app_sha256)

    authorization = None
    authorization_path: Path | None = None
    if arguments.public_authorization:
        authorization_path = _absolute_path(
            arguments.public_authorization, label="Public-release authorization"
        )
        authorization = inspect_public_authorization(
            authorization_path,
            app_sha256=app_sha256,
            release_version=release_version,
        )

    repository_evidence = inspect_repository(repository, runner)
    signature = inspect_signature(app, runner)
    notarization = inspect_notarization(app, runner)
    notices = inspect_notices(app)
    confirmed_tree = fingerprint_tree(app)
    if confirmed_tree != tree:
        raise EvidenceError(
            "App bundle changed during evidence collection; rebuild or stop concurrent packaging "
            "and collect again."
        )
    confirmed_repository = inspect_repository(repository, runner)
    if confirmed_repository != repository_evidence:
        raise EvidenceError(
            "Release repository changed during evidence collection; stop concurrent source "
            "changes and collect again."
        )

    final_file_evidence: list[tuple[Path, Mapping[str, object], str]] = []
    if zip_path is not None and distribution_zip is not None:
        final_file_evidence.append((zip_path, distribution_zip, "Distribution ZIP"))
    if license_path is not None and license_archive is not None:
        final_file_evidence.append((license_path, license_archive, "Licence archive"))
    final_file_evidence.extend(
        (path, sboms[label], f"SBOM {label}") for label, path in sbom_paths.items()
    )
    if clean_path is not None and clean_mac is not None:
        final_file_evidence.append((clean_path, clean_mac, "Clean-Mac evidence"))
    if authorization_path is not None and authorization is not None:
        final_file_evidence.append(
            (authorization_path, authorization, "Public-release authorization")
        )
    for evidence_path, evidence, label in final_file_evidence:
        confirmed = fingerprint_file(evidence_path, label=label)
        expected = {
            "sha256": evidence.get("sha256"),
            "size_bytes": evidence.get("size_bytes"),
        }
        if confirmed != expected:
            raise EvidenceError(
                f"{label} changed during evidence collection; collect again."
            )

    report: dict[str, object] = {
        "schema": REPORT_SCHEMA,
        "repository": repository_evidence,
        "application": {
            "name": app.name,
            "tree": tree,
            "bundle": bundle,
            "signature": signature,
            "notarization": notarization,
            "notices": notices,
        },
        "distribution_zip": distribution_zip,
        "sboms": sboms,
        "license_archive": license_archive,
        "clean_mac_evidence": clean_mac,
        "public_authorization": authorization,
    }
    failures = public_readiness_failures(report)
    report["public_readiness"] = {"ready": not failures, "failures": failures}
    return report


def atomic_write_json(
    path: Path, report: Mapping[str, object], *, overwrite: bool
) -> None:
    temporary_path: Path | None = None
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            prefix=f".{path.name}.",
            suffix=".tmp",
            dir=path.parent,
            delete=False,
        ) as stream:
            temporary_path = Path(stream.name)
            json.dump(report, stream, indent=2, sort_keys=True, allow_nan=False)
            stream.write("\n")
            stream.flush()
            os.fsync(stream.fileno())
        temporary_path.chmod(0o600)
        if path.is_symlink():
            raise EvidenceError(
                f"Refusing to publish through a symbolic-link report: {path}"
            )
        if overwrite:
            if path.exists():
                _lstat_regular(path, label="Existing evidence report")
            os.replace(temporary_path, path)
            temporary_path = None
        else:
            os.link(temporary_path, path)
            temporary_path.unlink()
            temporary_path = None
        try:
            directory_descriptor = os.open(path.parent, os.O_RDONLY)
            try:
                os.fsync(directory_descriptor)
            finally:
                os.close(directory_descriptor)
        except OSError:
            pass
    except FileExistsError as exc:
        raise EvidenceError(
            f"Evidence report already exists; use --overwrite explicitly: {path}"
        ) from exc
    except EvidenceError:
        raise
    except OSError as exc:
        raise EvidenceError(
            f"Could not publish evidence report atomically: {path}"
        ) from exc
    finally:
        if temporary_path is not None:
            try:
                temporary_path.unlink(missing_ok=True)
            except OSError:
                pass


def read_report(path: Path) -> Mapping[str, object]:
    _lstat_regular(path, label="Evidence report")
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise EvidenceError(f"Evidence report is not valid UTF-8 JSON: {path}") from exc
    return validate_report_structure(raw)


def extract_expected_checksums_from_report(
    report: Mapping[str, object],
) -> dict[str, str]:
    """Extract expected asset checksums from a structured release evidence report."""
    expected: dict[str, str] = {}
    sboms = report.get("sboms")
    if isinstance(sboms, Mapping):
        for label, sbom in sboms.items():
            if (
                isinstance(sbom, Mapping)
                and "sha256" in sbom
                and isinstance(sbom["sha256"], str)
            ):
                expected[f"{label}.cdx.json"] = sbom["sha256"]
    license_archive = report.get("license_archive")
    if (
        isinstance(license_archive, Mapping)
        and "sha256" in license_archive
        and isinstance(license_archive["sha256"], str)
    ):
        expected["dependency-licences.zip"] = license_archive["sha256"]
    return expected


def verify_release_assets(
    assets_directory: Path,
    expected_checksums: Mapping[str, str],
) -> dict[str, object]:
    """Verify that release assets in a directory match their expected SHA-256 digests."""
    if not assets_directory.is_dir():
        raise EvidenceError(
            f"Assets directory does not exist or is not a directory: {assets_directory}"
        )
    if not expected_checksums:
        raise EvidenceError("No expected asset checksums provided for verification.")

    verified: list[dict[str, object]] = []
    failures: list[str] = []

    for name, expected_sha256 in sorted(expected_checksums.items()):
        if (
            not name
            or Path(name).name != name
            or ".." in Path(name).parts
            or Path(name).is_absolute()
        ):
            failures.append(
                f"Release asset name '{name}' must be a simple filename without path traversal"
            )
            continue

        try:
            asset_path = (assets_directory / name).resolve()
            asset_path.relative_to(assets_directory.resolve())
        except (ValueError, RuntimeError):
            failures.append(
                f"Release asset name '{name}' escapes assets directory: {assets_directory}"
            )
            continue

        if not _is_sha256(expected_sha256):
            failures.append(f"Invalid expected SHA-256 for '{name}': {expected_sha256}")
            continue

        if not asset_path.exists():
            failures.append(
                f"Missing required release asset: '{name}' in {assets_directory}"
            )
            continue

        if asset_path.is_symlink() or not asset_path.is_file():
            failures.append(
                f"Release asset '{name}' must be a regular file, not a symlink or directory: {asset_path}"
            )
            continue

        try:
            fp = fingerprint_file(asset_path, label=f"Release asset '{name}'")
            observed_sha256 = fp["sha256"]
            size_bytes = fp["size_bytes"]
            if observed_sha256 != expected_sha256.lower():
                failures.append(
                    f"Checksum mismatch for '{name}': expected {expected_sha256.lower()}, "
                    f"observed {observed_sha256}"
                )
                verified.append(
                    {
                        "name": name,
                        "expected_sha256": expected_sha256.lower(),
                        "observed_sha256": observed_sha256,
                        "size_bytes": size_bytes,
                        "status": "mismatch",
                    }
                )
            else:
                verified.append(
                    {
                        "name": name,
                        "sha256": observed_sha256,
                        "size_bytes": size_bytes,
                        "status": "matched",
                    }
                )
        except EvidenceError as exc:
            failures.append(f"Asset '{name}' error: {exc}")

    return {
        "valid": len(failures) == 0,
        "verified": verified,
        "failures": failures,
    }


def _print_readiness(
    report: Mapping[str, object], *, public_ready: bool, stored_report: bool = False
) -> int:
    readiness = report["public_readiness"]
    assert isinstance(readiness, Mapping)
    failures = readiness["failures"]
    assert isinstance(failures, list)
    if readiness["ready"] is True:
        if stored_report:
            print("Recorded public release evidence: READY (not live-verified)")
            if public_ready:
                print(
                    "Action needed: stored unsigned JSON cannot establish current public "
                    "readiness; rerun collect --public-ready against the live artifacts.",
                    file=sys.stderr,
                )
                return 2
        else:
            print("Public release gate: READY")
        return 0
    print(f"Public release gate: NOT READY ({len(failures)} requirements unmet)")
    if public_ready:
        for failure in failures:
            print(f"  - {failure}", file=sys.stderr)
        return 2
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    arguments = _parser().parse_args(argv)
    try:
        if arguments.command == "collect":
            output = _absolute_path(arguments.output, label="Output report")
            validate_collect_output(arguments, output)
            report = collect_report(arguments)
            atomic_write_json(output, report, overwrite=arguments.overwrite)
            print(f"Wrote release evidence: {output}")
            return _print_readiness(report, public_ready=arguments.public_ready)
        if arguments.command == "check":
            report_path = _absolute_path(arguments.report, label="Evidence report")
            report = read_report(report_path)
            print(f"Evidence report is structurally valid: {report_path}")
            return _print_readiness(
                report, public_ready=arguments.public_ready, stored_report=True
            )
        if arguments.command == "verify-assets":
            directory = _absolute_path(arguments.directory, label="Assets directory")
            if not arguments.checksums and not arguments.report:
                raise EvidenceError(
                    "Specify either --checksums or --report to verify release assets."
                )
            expected: dict[str, str] = {}
            if arguments.report:
                report_path = _absolute_path(arguments.report, label="Evidence report")
                report = read_report(report_path)
                expected.update(extract_expected_checksums_from_report(report))
            if arguments.checksums:
                checksums_path = _absolute_path(
                    arguments.checksums, label="Checksums JSON"
                )
                _lstat_regular(checksums_path, label="Checksums JSON")
                try:
                    loaded = json.loads(checksums_path.read_text(encoding="utf-8"))
                    if not isinstance(loaded, Mapping):
                        raise EvidenceError(
                            "Checksums file must contain a JSON object mapping filename to SHA-256."
                        )
                    for k, v in loaded.items():
                        str_k, str_v = str(k), str(v).lower()
                        if str_k in expected and expected[str_k].lower() != str_v:
                            raise EvidenceError(
                                f"Conflicting expected SHA-256 for '{str_k}': report specifies "
                                f"{expected[str_k]}, checksums file specifies {str_v}"
                            )
                        expected[str_k] = str_v
                except (OSError, UnicodeError, json.JSONDecodeError) as exc:
                    raise EvidenceError(
                        f"Checksums file is not valid UTF-8 JSON: {checksums_path}"
                    ) from exc

            result = verify_release_assets(directory, expected)
            for item in result["verified"]:
                status = item["status"]
                name = item["name"]
                if status == "matched":
                    print(f"  [OK] {name}: {item['sha256']}")
                else:
                    print(
                        f"  [MISMATCH] {name}: expected {item.get('expected_sha256')}, "
                        f"got {item.get('observed_sha256')}",
                        file=sys.stderr,
                    )
            if not result["valid"]:
                for failure in result["failures"]:
                    print(f"Action needed: {failure}", file=sys.stderr)
                return 2
            print(
                f"All {len(result['verified'])} release assets verified successfully."
            )
            return 0
        raise EvidenceError(f"Unknown command: {arguments.command}")
    except EvidenceError as exc:
        print(f"Action needed: {exc}", file=sys.stderr)
        return 2
    except KeyboardInterrupt:
        print(
            "Evidence collection cancelled; no partial report was published.",
            file=sys.stderr,
        )
        return 130


if __name__ == "__main__":
    raise SystemExit(main())
